---

- name: Add HAProxy 1.8 PPA
  apt_repository:
    repo: "ppa:vbernat/haproxy-1.8"

- name: Install HAProxy
  package:
    name: haproxy
    state: latest

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify:
    - restart haproxy
