---

- name: Install Apache2
  package:
    name: apache2
    state: latest

- name: Enable/start Apache service
  service:
    name: apache2
    state: started

- name: Define custom log format
  lineinfile:
    path: /etc/apache2/apache2.conf
    line: 'LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" forwarded'
    insertafter: '^LogFormat'
  notify: restart apache2

- name: Override default log format
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: "^\tCustomLog"
    line: "\tCustomLog ${APACHE_LOG_DIR}/access.log forwarded"
  notify: restart apache2

- name: Overwrite default index.html
  copy:
    dest: /var/www/html/index.html
    content: "{{ html_content }}\n"
    backup: yes
